version: '3.6'
services:
    main:
        container_name: niris
        image: intersystemsdc/iris-ml-community:latest
        restart: always
        hostname: 'iris'
        init: true
        expose:
            - '1972'
            - '52773'
        ports:
            - '9091:1972'
            - '9092:52773'
        volumes:
            - ./irconfig:/irconfig
        command: --password-file /irconfig/password.txt
    nodered:
        container_name: nodered
        hostname: 'nodered'
        image: caretdev/node-red
        ports:
            - "1880:1880"
        volumes:
            - ./data:/data